export const VOICE_CONFIG={
CHECK_IN_MESSAGE:"Are you still focused?",
RECORDING_DURATION_MS:3000,
MAX_RECORDING_DURATION_MS:10000,
CLOSING_DELAY_MS:1000,
API_TIMEOUT_MS:15000,
MAX_RETRY_COUNT:2,
AUTO_STOP_ON_SILENCE:false,
SILENCE_TIMEOUT_MS:2000
};